name: atsign_atmosphere_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.13
  cupertino_icons: ^0.1.3
  file_picker: ^2.0.10
  filesystem_picker: ^1.0.3
  flushbar: ^1.10.4
  flutter_keychain: ^1.0.0
  flutter_local_notifications: ^2.0.1
  flutter_qr_reader: ^1.0.3
  flutter_slidable: ^0.6.0
  google_fonts: ^1.1.0
  intl: ^0.16.1
  open_file: ^3.0.3
  pedantic: ^1.11.0
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2
  qr_flutter: ^3.2.0
  receive_sharing_intent: ^1.4.1
  rxdart: ^0.24.1
  share: ^0.6.5+2
  url_launcher: ^5.7.10
  video_thumbnail: ^0.2.2
  webview_flutter: ^1.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.0+2

  # at_onboarding_flutter: ^1.0.0+3
  at_onboarding_flutter:
    path: /Users/sachinsingh/Documents/geekyAnts/AtSign/at_widgets/at_onboarding_flutter
  at_client_mobile: ^1.0.0+9
  at_commons: ^1.0.1+6
  at_contact: ^1.0.0+3
  at_lookup: ^1.0.0+6
  atsign_authentication_helper:
  # at_contacts_flutter:
  # at_common_flutter:
  at_common_flutter: ^1.0.0
    # path: /Users/sachinsingh/Documents/geekyAnts/AtSign/at_widgets/at_common_flutter
    # git:
    #   url: https://github.com/atsign-foundation/at_widgets.git
    #   path: at_common_flutter
    #   ref: dev_env

  at_contacts_flutter:
    path: /Users/sachinsingh/Documents/geekyAnts/AtSign/at_widgets/at_contacts_flutter
    # git:
    #   url: https://github.com/atsign-foundation/at_widgets.git
    #   path: at_contacts_flutter
    #   ref: dev_env
  at_contacts_group_flutter: ^1.0.0
    # path: /Users/sachinsingh/Documents/geekyAnts/AtSign/at_widgets/at_contacts_group_flutter
    # git:
    #   url: https://github.com/atsign-foundation/at_widgets.git
    #   path: at_contacts_group_flutter
    #   ref: dev_env
dependency_overrides:
  at_contacts_flutter:
    path: /Users/sachinsingh/Documents/geekyAnts/AtSign/at_widgets/at_contacts_flutter
  at_client:
    path: /Users/sachinsingh/Documents/geekyAnts/AtSign/at_client_sdk/at_client
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: dev_env
      version: ^1.0.0+4
  crypto: ^2.1.5
  crypton: ^2.0.1
  uuid: ^3.0.4
  hive: ^2.0.4
  pointycastle: ^2.0.0
  asn1lib: ^0.8.1
  flutter_slidable: ^0.6.0
  file_picker: ^3.0.1
  archive: ^3.1.2
  path_provider: ^2.0.1
  share: ^2.0.1
  plugin_platform_interface: ^2.0.0
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: file_transfer
      version: ^1.0.1+4
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: dev_env
      version: ^1.0.1+4
  at_common_flutter: ^1.0.0    

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeu
      fonts:
        - asset: assets/fonts/HelveticaLight.ttf
          weight: 300
        - asset: assets/fonts/HelveticaMedium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaRegular.ttf
          weight: 400
        - asset: assets/fonts/HelveticaBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaExtraBold.ttf
          weight: 800
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
